# Generated by Django 3.0.6 on 2020-05-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.CharField(max_length=1024)),
                ('tweet_word_set', models.CharField(max_length=1024)),
                ('tweet_link', models.CharField(max_length=128)),
                ('user_id', models.CharField(max_length=32)),
                ('user_name', models.CharField(max_length=64)),
                ('user_screen_name', models.CharField(max_length=64)),
                ('user_profile_url', models.CharField(max_length=128)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tweets',
            },
        ),
    ]
